FROM centos:6
MAINTAINER yidwu@cisco.com
COPY sd.rpm /tmp/sd.rpm
RUN rpm -ivh /tmp/sd.rpm
RUN curl \
    --url http://lwr-linux.cisco.com/yum.repos.d/CentOS-Base-6.repo   -o /etc/yum.repos.d/CentOS-Base.repo         \
    --url http://lwr-linux.cisco.com/yum.repos.d/epel-6.repo          -o /etc/yum.repos.d/epel.repo                \
    --url http://lwr-linux.cisco.com/yum.repos.d/puppetlabs-el6.repo  -o /etc/yum.repos.d/puppetlabs.repo          \
    --url http://lwr-linux.cisco.com/yum.repos.d/lwr-dbds-nexus1.repo -o /etc/yum.repos.d/lwr-dbds-nexus1.repo     \
    --url http://lwr-linux.cisco.com/yum.repos.d/ius-centos6.repo     -o /etc/yum.repos.d/ius.repo                 \
    && yum clean all --enablerepo=\*
    && yum -y install augeas \
    && augtool setm '/files/etc/yum/pluginconf.d/*/main' enabled false \
    && yum -y update \
    && yum -y groupinstall development \
    && yum -y groupinstall 'Buildsystem building group' \
    && yum -y install \
        java-1.7.0-openjdk-devel \
        java-1.7.0-openjdk \
        yum-utils \
        crudini \
        unzip \
        wget \
    && yum clean all --enablerepo=\*
COPY run_sd.sh /tmp/run_sd.sh
ENTRYPOINT ["/tmp/run_sd.sh"]
EXPOSE 2015 2181 2888 3888
CMD ["--help"]