package com.cisco.oss.foundation.directory.entity;

public enum ActionType{
	NEW,
	UPDATE,
	UPDATE_URI,
	UPDATE_STATUS,
	UPDATE_INTERNAL_STATUS,
	UPDATE_SECRET,
	UPDATE_ACL,
	DELETE,
	LOCK,
	ASSOC_INSTANCE,
	DISASSOC_INSTANCE,
	UPDATE_INSTANCE,
	ASSOC_SESSION,
	DISASSOC_SESSION,
	;
}